services:
  postgres:
    image: postgres:16-alpine
    container_name: korp-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: korp
      POSTGRES_PASSWORD: korp123
      POSTGRES_DB: usuario_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U korp -d usuario_db"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  pgdata:
